apiVersion: apps/v1
kind: Deployment
metadata:
  name: outbox-publisher
  namespace: rekreativko
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: outbox-publisher
  template:
    metadata:
      labels:
        app: outbox-publisher
    spec:
      containers:
        - name: outbox-publisher
          image: rekreativko/outbox-publisher:latest
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
          env:
            - name: SERVICE_NAME
              value: "outbox-publisher"
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: 8082
          #   initialDelaySeconds: 5
          #   periodSeconds: 5
          # liivenessProbe:
          #   httpGet:
          #     path: /health
          #     port: 8082
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
