services:
  gateway:
    build:
      context: .
      dockerfile: ./build/Dockerfile
      args:
        SERVICE: gateway
        CMD_PATH: api
    image: rekreativko/gateway:latest

  identity:
    build:
      context: .
      dockerfile: ./build/Dockerfile
      args:
        SERVICE: identity
        CMD_PATH: api
    image: rekreativko/identity:latest

  account-profile:
    build:
      context: .
      dockerfile: ./build/Dockerfile
      args:
        SERVICE: account-profile
        CMD_PATH: api
    image: rekreativko/account-profile:latest

  activity:
    build:
      context: .
      dockerfile: ./build/Dockerfile
      args:
        SERVICE: activity
        CMD_PATH: api
    image: rekreativko/activity:latest

  activity-cron:
    build:
      context: .
      dockerfile: ./build/Dockerfile
      args:
        SERVICE: activity
        CMD_PATH: cron
    image: rekreativko/activity-cron:latest

  notifications:
    build:
      context: .
      dockerfile: ./build/Dockerfile
      args:
        SERVICE: notifications
        CMD_PATH: api
    image: rekreativko/notifications:latest

  outbox-publisher:
    build:
      context: .
      dockerfile: ./build/Dockerfile
      args:
        SERVICE: outbox-publisher
        CMD_PATH: worker
    image: rekreativko/outbox-publisher:latest
