apiVersion: v1
kind: Service
metadata:
  name: account-profile-service
  namespace: rekreativko
spec:
  selector:
    app: account-profile
  ports:
    - port: 8082
      targetPort: 8082
  type: ClusterIP
