apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: rekreativko
data:
  # Database
  POSTGRES_HOST: postgres-service
  POSTGRES_PORT: "5432"
  POSTGRES_DB: rekreativko
  POSTGRES_MAX_OPEN_CONN: "5"
  POSTGRES_MAX_IDLE_CONN: "5"

  # Nats
  NATS_URL: nats://nats-service:4222

  # Redis
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  REDIS_MAX_RETRIES: "3"
  REDIS_POOL_SIZE: "10"

  # Telemetry
  OTEL_EXPORTER_OTLP_ENDPOINT: jaeger:4318
  TELEMETRY_ENABLED: "true"
  OTEL_TRACES_SAMPLER_ARG: "1.0"

  # Metrics
  METRICS_ENABLED: "true"

  # Service URLs
  IDENTITY_SERVICE_URL: http://identity-service:8081
  ACCOUNT_PROFILE_SERVICE_URL: http://account-profile-service:8082

  # JWT
  JWT_ACCESS_TOKEN_DURATION: "72h"
  JWT_REFRESH_TOKEN_DURATION: "360h"

  # Log
  LOG_LEVEL: "debug"
  LOG_FORMAT: "json"

  # Jaeger
  COLLECTOR_OTLP_ENABLED: "true"
  SPAN_STORE_TYPE: "memory"

  # Grafana
  GF_AUTH_ANONYMOUS_ENABLED: "true"
  GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
  GF_SECURITY_ADMIN_PASSWORD: "admin"
  GF_INSTALL_PLUGINS: grafana-piechart-panel

  ENVIRONMENT: "development"
  DEV_MODE: "true"
