apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: rekreativko
type: Opaque
data:
  DATABASE_USERNAME: cG9zdGdyZXM=
  DATABASE_PASSWORD: cG9zdGdyZXM=

  GATEWAY_API_KEYS: NDY4MDE5YjUtYTg2My00ZTQ5LWI4ZDgtMmM0MjAwNzlhYzdi
  GATEWAY_API_KEY: NDY4MDE5YjUtYTg2My00ZTQ5LWI4ZDgtMmM0MjAwNzlhYzdi

  JWT_SECRET: c2QzTnRTNXZaR1NnTlB5b1RnMWZuZTBiYjJ2b3l1bVdJN251NUNWcmk4VXI5Y3U1VmJWajhkV2xRelp3QkJU
