apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rekreativko-root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  source:
    repoURL: https://github.com/rasparac/rekreativko-api.git
    targetRevision: HEAD
    path: argocd/apps

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true # delete resources removed from git
      selfHeal: true # revert manual changes to cluster
    syncOptions:
      - CreateNamespace=true # create namespace if not exists
      - ApplyOutOfSyncOnly=true

    retry:
      limit: 5
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 3m # the maximum amount of time allowed for the backoff strategy
