// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/my/profile": {
            "get": {
                "security": [
                    {
                        "BearerAuth": [],
                        "GatewayKeyAuth": []
                    }
                ],
                "description": "Returns account profile",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account Profile"
                ],
                "summary": "Returns account profile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Account ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Account returned successfully",
                        "schema": {
                            "$ref": "#/definitions/api.Response-any"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/api.Response-any"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/api.Response-any"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": [],
                        "GatewayKeyAuth": []
                    }
                ],
                "description": "Update account profile by id and data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account Profile"
                ],
                "summary": "Update account profile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Profile account ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Account created successfully",
                        "schema": {
                            "$ref": "#/definitions/api.Response-any"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/api.Response-any"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/api.Response-any"
                        }
                    }
                }
            }
        },
        "/api/v1/my/settings": {
            "get": {
                "security": [
                    {
                        "BearerAuth": [],
                        "GatewayKeyAuth": []
                    }
                ],
                "description": "Returns account account settings for logged in account",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account Profile"
                ],
                "summary": "Returns account account settings",
                "responses": {
                    "200": {
                        "description": "Account settings returned successfully",
                        "schema": {
                            "$ref": "#/definitions/api.Response-github_com_rasparac_rekreativko-api_account-profile_internal_interfaces_http_dtos_Setting"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/api.Response-any"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/api.Response-any"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": [],
                        "GatewayKeyAuth": []
                    }
                ],
                "description": "Update account settings by id and data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account Profile"
                ],
                "summary": "Update account settings",
                "parameters": [
                    {
                        "description": "Account Settings Data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_rasparac_rekreativko-api_account-profile_internal_interfaces_http_dtos.UpdateAccountSettingsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Account settings updated successfully",
                        "schema": {
                            "$ref": "#/definitions/api.Response-any"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/api.Response-any"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/api.Response-any"
                        }
                    }
                }
            }
        },
        "/api/v1/profiles": {
            "get": {
                "security": [
                    {
                        "BearerAuth": [],
                        "GatewayKeyAuth": []
                    }
                ],
                "description": "Returns account profiles filtered by query parameters",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account Profile"
                ],
                "summary": "Returns account profiles",
                "parameters": [
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "Filter by account IDs (can be repeated)",
                        "name": "account_id",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "Filter by nicknames (can be repeated)",
                        "name": "nickname",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Date of birth after (YYYY-MM-DD)",
                        "name": "dob_gt",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Date of birth before (YYYY-MM-DD)",
                        "name": "dob_lt",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Include deleted profiles",
                        "name": "include_deleted",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort field (e.g. created_at, nickname)",
                        "name": "sort_by",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort order (asc, desc)",
                        "name": "sort_order",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by location country",
                        "name": "country",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Limit number of results (default 20)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset for pagination (default 0)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.Response-any"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/api.Response-any"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/api.Response-any"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.APIError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "invalid_request"
                },
                "details": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "message": {
                    "type": "string",
                    "example": "Invalid request"
                }
            }
        },
        "api.Response-any": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "only on success"
                },
                "error": {
                    "description": "only on error",
                    "allOf": [
                        {
                            "$ref": "#/definitions/api.APIError"
                        }
                    ]
                },
                "message": {
                    "type": "string",
                    "example": "Operation completed successfully"
                },
                "status": {
                    "type": "string",
                    "example": "success"
                },
                "timestamp": {
                    "type": "string",
                    "example": "2020-01-01T00:00:00Z"
                }
            }
        },
        "api.Response-github_com_rasparac_rekreativko-api_account-profile_internal_interfaces_http_dtos_Setting": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "only on success",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_rasparac_rekreativko-api_account-profile_internal_interfaces_http_dtos.Setting"
                        }
                    ]
                },
                "error": {
                    "description": "only on error",
                    "allOf": [
                        {
                            "$ref": "#/definitions/api.APIError"
                        }
                    ]
                },
                "message": {
                    "type": "string",
                    "example": "Operation completed successfully"
                },
                "status": {
                    "type": "string",
                    "example": "success"
                },
                "timestamp": {
                    "type": "string",
                    "example": "2020-01-01T00:00:00Z"
                }
            }
        },
        "github_com_rasparac_rekreativko-api_account-profile_internal_interfaces_http_dtos.Setting": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string",
                    "example": "notification"
                },
                "description": {
                    "type": "string",
                    "example": "Enable or disable email notifications"
                },
                "label": {
                    "type": "string",
                    "example": "Email Notifications"
                },
                "type": {
                    "type": "string",
                    "example": "boolean"
                },
                "value": {
                    "type": "string",
                    "example": "true"
                }
            }
        },
        "github_com_rasparac_rekreativko-api_account-profile_internal_interfaces_http_dtos.UpdateAccountSettingsRequest": {
            "type": "object",
            "properties": {
                "settings": {
                    "description": "Settings is a map of setting keys to their values\nExample: {\"notification.email.enabled\": true, \"preference.language\": \"en\"}",
                    "type": "object"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        },
        "GatewayKeyAuth": {
            "description": "Key added automatically by the gateway when proxying requests; required directly here only when bypassing the gateway.",
            "type": "apiKey",
            "name": "X-Gateway-Key",
            "in": "header"
        }
    },
    "security": [
        {
            "GatewayKeyAuth": []
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Account Profile Service API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
